### ISSUE TITLE
Detection reproduction

### ISSUE THREAD

**Issue by toyot-li** [xiaoaoran/polarmix#1]
@xiaoaoran Hi, the paper said you apply your method to object detection based on the OpenPCDet toolbox, where is the code? It is also noticed the compared baseline is much lower than OpenPCDet released results (such as pointpillars). I hope to see the code and checkpoints/logs for reproduction. Thanks.

**Comment by xiaoaoran** [comment]
Thanks for your comments.

We would clarify that this paper mainly focuses on semantic segmentation task. This work also conducted preliminary experiments on the task of object detection to verify the effectiveness of PolarMix, e.g., simple experiments with OpenPCDet repo.  As for the baseline,  this work only used two GPUs (instead of 8 GPUs in the OpenPCDet)  for training due to resource constrain and removed some data augmentation processes for faster and simple implementations of experiments. So the baseline performance is a bit lower as compared with OpenPCDet released results. For a fair comparison,  this work directly implemented polarmix on top of the baseline.

**Comment by toyot-li** [comment]
The method is claimed to be **generic but can mitigate the data constraint effectively across different perception tasks and scenarios**, **Extensive experiments show that PolarMix achieves superior performance consistently across different perception tasks and scenarios**.

Moreover, in another relevant issue #2, the segmentation task also adopts a low baseline.

**Comment by Petros626** [comment]
@toyot-li can be PolarMix used for normal point clouds like KITTI? 
@xiaoaoran does this repo is still supported?
